/* ==========================================================================
   ELITE THREAD — Product & Category Data
   ==========================================================================
   This is the ONLY file you need to touch to add, edit or remove a product.

   TO ADD A PRODUCT:
   1. Add image(s) to /images/products/ named like: et-00X-1.jpg, et-00X-2.jpg
   2. Copy one object below, give it a new unique "id", fill in the fields.
   3. Save. It will automatically appear in Shop, its category page, search,
      related products, and Featured / New Arrivals sections if flagged.

   FIELD NOTES:
   - price: number only (no commas/currency symbol) — formatted at display time
   - category: must exactly match a "slug" from CATEGORIES below
   - type: subcategory label, shown on product cards (free text, keep short)
   - images: array of paths, first image is the primary/cover image
   - keywords: extra searchable terms (colours, styles, alt names)
   - available: set to false to show "Currently Unavailable" and disable orders
   ========================================================================== */

const CATEGORIES = [
  {
    slug: "casual-wear",
    name: "Casual Wear",
    page: "categories/casual-wear.html",
    intro: "Everyday pieces built around comfort, movement and a bit of edge — the wear for the days you're not reporting to anyone."
  },
  {
    slug: "official-wear",
    name: "Official Wear",
    page: "categories/official-wear.html",
    intro: "Smart, considered pieces for the office and the occasions after it — sharp without trying too hard."
  },
  {
    slug: "footwear",
    name: "Footwear",
    page: "categories/footwear.html",
    intro: "Sneakers, boots, trainers and slides — the collection that carries everything else."
  },
  {
    slug: "mens-clothing",
    name: "Men's Clothing",
    page: "categories/mens-clothing.html",
    intro: "Polos, jeans, shirts and layers built for the everyday Nairobi rotation."
  },
  {
    slug: "mens-footwear",
    name: "Men's Footwear",
    page: "categories/mens-footwear.html",
    intro: "Boots, sneakers, trainers and slippers, chosen for how they'll actually get worn."
  },
  {
    slug: "accessories",
    name: "Accessories",
    page: "categories/accessories.html",
    intro: "The finishing details — coming soon to ELITE THREAD."
  }
];

const PRODUCTS = [
  {
    id: "et-001",
    name: "Wallabee-Style Boot — Cream Suede, Orange Shearling",
    category: "mens-footwear",
    type: "Boots",
    brand: "",
    price: 3500,
    currency: "KES",
    color: "Cream",
    images: ["images/products/et-001-1.jpg", "images/products/et-001-2.jpg"],
    shortDescription: "A cream suede boot with orange shearling trim, built for cold mornings and long days.",
    description: "A cream suede boot finished with warm orange shearling at the collar. The moc-toe construction and crepe-style sole bring a relaxed, worn-in character from the first wear. Pairs equally well with jeans or tapered trousers.",
    keywords: ["boots", "wallabee", "cream boots", "suede boots", "men's footwear", "shearling"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-002",
    name: "Casual Sneaker — Light Blue",
    category: "mens-footwear",
    type: "Sneakers",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Light Blue",
    images: ["images/products/et-002-1.jpg"],
    shortDescription: "A light blue casual sneaker for everyday wear. Price to be confirmed.",
    description: "A light blue low-top sneaker with a clean, casual silhouette that goes with almost anything in the everyday rotation. Message us on WhatsApp for current pricing and availability.",
    keywords: ["sneakers", "light blue sneaker", "casual sneaker", "men's footwear"],
    featured: true,
    newArrival: false,
    available: true
  },
  {
    id: "et-003",
    name: "Men's Polo Shirt",
    category: "mens-clothing",
    type: "Polo Shirts",
    brand: "",
    price: 1300,
    currency: "KES",
    color: "White, Blue, Black, Beige",
    images: ["images/products/et-003-1.jpg"],
    shortDescription: "A classic polo shirt, available in four colourways.",
    description: "A wardrobe staple cut for a clean, everyday fit. Available in white, blue, black and beige — order the colour you'd like via WhatsApp.",
    keywords: ["polo", "polo shirt", "men's clothing", "casual wear", "white polo", "blue polo", "black polo", "beige polo"],
    featured: true,
    newArrival: false,
    available: true
  },
  {
    id: "et-004",
    name: "Crocodile-Embroidered Slippers — Black & Grey",
    category: "mens-footwear",
    type: "Slippers",
    brand: "",
    price: 3500,
    currency: "KES",
    color: "Black, Grey",
    images: ["images/products/et-004-1.jpg"],
    shortDescription: "Black and grey slides with a crocodile embroidery detail.",
    description: "A slide built for comfort with a black and grey colourway and a crocodile embroidery detail across the strap. An easy everyday off-duty piece.",
    keywords: ["slippers", "slides", "crocodile", "men's footwear", "black slides"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-005",
    name: "CRUX Jeans — Tan / Beige",
    category: "mens-clothing",
    type: "Jeans",
    brand: "CRUX",
    price: 1500,
    currency: "KES",
    color: "Tan / Beige",
    images: ["images/products/et-005-1.jpg"],
    shortDescription: "A tan/beige straight-leg jean from CRUX.",
    description: "A tan and beige jean cut for an easy, everyday fit. A versatile neutral that carries from casual to smart-casual with the right top layer.",
    keywords: ["jeans", "crux", "tan jeans", "beige jeans", "men's clothing", "casual wear"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-006",
    name: "Shox-Style Trainer — Black with Turquoise Accents",
    category: "mens-footwear",
    type: "Trainers",
    brand: "",
    price: 3800,
    currency: "KES",
    color: "Black / Turquoise",
    images: ["images/products/et-006-1.jpg"],
    shortDescription: "A black trainer with turquoise accents and a visible cushioned sole.",
    description: "A black trainer with turquoise accent detailing and a visible cushioned sole unit for all-day comfort. A statement piece for anyone who wants their footwear doing some of the talking.",
    keywords: ["trainers", "shox", "black trainers", "turquoise", "men's footwear", "sneakers"],
    featured: true,
    newArrival: false,
    available: true
  },

  /* ------------------------------------------------------------------
     NEW BATCH — added from supplied product photos.
     ⚠️ PRICES NOT YET SUPPLIED: every item below is set to
     priceOnRequest: true, which displays "Price on request" on the site.
     Replace with e.g.  price: 2500,  and delete the priceOnRequest line
     once you've confirmed each price.
     ------------------------------------------------------------------ */

  {
    id: "et-007",
    name: "Ripped Skinny Jeans — Black",
    category: "mens-clothing",
    type: "Jeans",
    brand: "",            // tag reads OBEY — confirm before claiming the brand
    price: 0,
    priceOnRequest: true, // ⚠️ set the real price here
    currency: "KES",
    color: "Black",
    sizes: "30–36",
    images: ["images/products/et-007-1.jpg"],
    shortDescription: "Black skinny-fit jeans with distressed knee detailing. Sizes 30–36.",
    description: "A black skinny-fit jean with distressed detailing at the knees and a slim taper through the leg. Available in sizes 30 to 36 — let us know your size on WhatsApp.",
    keywords: ["jeans", "black jeans", "ripped jeans", "distressed", "skinny jeans", "men's clothing", "casual wear"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-008",
    name: "Suede Combat Boot — Tan",
    category: "mens-footwear",
    type: "Boots",
    brand: "",
    price: 0,
    priceOnRequest: true, // ⚠️ set the real price here
    currency: "KES",
    color: "Tan / Coyote",
    sizes: "",            // add available sizes when confirmed
    images: ["images/products/et-008-1.jpg"],
    shortDescription: "A tan suede military-style combat boot with reinforced nylon panels.",
    description: "A high-cut combat boot in tan suede with breathable nylon side panels, speed-lace hardware and a rugged lugged sole. Built for hard wear and long days on your feet.",
    keywords: ["boots", "combat boots", "tan boots", "suede boots", "military boots", "men's footwear"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-009",
    name: "Shox-Style Trainer — Black & Grey",
    category: "mens-footwear",
    type: "Trainers",
    brand: "",
    price: 0,
    priceOnRequest: true, // ⚠️ set the real price here
    currency: "KES",
    color: "Black / Grey",
    sizes: "",
    images: ["images/products/et-009-1.jpg"],
    shortDescription: "A dark grey trainer with a visible cushioned column sole.",
    description: "A dark grey and black trainer with a visible cushioned column sole unit and reflective side detailing. An everyday trainer with a bit of presence.",
    keywords: ["trainers", "shox", "black trainers", "grey trainers", "sneakers", "men's footwear"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-010",
    name: "Straight-Leg Jeans — Dark Blue",
    category: "mens-clothing",
    type: "Jeans",
    brand: "",            // tag reads ND / New Design — confirm before listing
    price: 0,
    priceOnRequest: true, // ⚠️ set the real price here
    currency: "KES",
    color: "Dark Blue",
    sizes: "34",          // photographed pair is size 34 — add others if stocked
    images: ["images/products/et-010-1.jpg"],
    shortDescription: "Dark indigo straight-leg jeans with contrast tan stitching.",
    description: "A dark indigo jean with contrast tan stitching and a clean straight-leg cut. A smarter denim option that works for casual Fridays as easily as weekends.",
    keywords: ["jeans", "blue jeans", "dark denim", "straight leg", "men's clothing", "casual wear"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-011",
    name: "Ribbed Zip Cardigan — Navy & Khaki",
    category: "mens-clothing",
    type: "Jackets",
    brand: "",
    price: 0,
    priceOnRequest: true, // ⚠️ set the real price here
    currency: "KES",
    color: "Navy / Khaki",
    sizes: "XL, 2XL",
    images: ["images/products/et-011-1.jpg"],
    shortDescription: "A ribbed knit zip-through cardigan in brown with cream raglan sleeves. XL and 2XL.",
    description: "A ribbed knit zip-through cardigan in warm brown, with contrast cream raglan sleeves and a funnel neck. Side pockets and a full-length zip make it an easy layer for cooler mornings. Available in XL and 2XL.",
    keywords: ["cardigan", "knitwear", "sweater", "jacket", "zip up", "brown", "layers", "men's clothing", "casual wear"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-012",
    name: "Shox-Style Sneaker — Red",
    category: "mens-footwear",
    type: "Sneakers",
    brand: "",
    price: 0,
    priceOnRequest: true, // ⚠️ set the real price here
    currency: "KES",
    color: "Red / Black",
    sizes: "40–45",
    images: ["images/products/et-012-1.jpg"],
    shortDescription: "A bold red sneaker with a black cushioned column sole. Sizes 40–45.",
    description: "A bold red sneaker with moulded overlays and a black cushioned column sole unit. A statement piece for anyone who'd rather their shoes lead the outfit. Available in sizes 40 to 45.",
    keywords: ["sneakers", "red sneakers", "shox", "trainers", "men's footwear"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-013",
    name: "Oversized Print Tee",
    category: "mens-clothing",
    type: "T-Shirts",
    brand: "",
    price: 0,
    priceOnRequest: true, // ⚠️ set the real price here
    currency: "KES",
    color: "Black, Brown, Tan, Rust, White",
    sizes: "",
    images: ["images/products/et-013-1.jpg"],
    shortDescription: "An oversized cotton tee with a splash-print graphic. Five colourways.",
    description: "A relaxed, oversized cotton tee with a bold splash-print graphic across the chest and drop shoulders. Available in black, brown, tan, rust and white — tell us your colour and size on WhatsApp.",
    keywords: ["t-shirt", "tee", "oversized", "print tee", "graphic tee", "casual wear", "men's clothing"],
    featured: true,
    newArrival: true,
    available: true
  },


  {
    id: "et-014",
    name: "Technical Runner Sneaker — Light Grey / Sage",
    category: "mens-footwear",
    type: "Sneakers",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Light Grey / Sage",
    sizes: "",
    images: ["images/products/et-014-1.jpg"],
    shortDescription: "A light grey and sage technical-style runner with a layered upper.",
    description: "A lightweight-looking runner with a layered light grey and sage upper, contrasting panels and a modern athletic silhouette. Ask us about available sizes and current price.",
    keywords: ["sneakers", "runner", "running shoe", "technical sneaker", "grey sneaker", "sage", "men's footwear"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-015",
    name: "Suede Outdoor Slip-On",
    category: "mens-footwear",
    type: "Slip-Ons",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Yellow, Brown, Black",
    sizes: "",
    images: ["images/products/et-015-1.jpg", "images/products/et-015-2.jpg", "images/products/et-015-3.jpg"],
    shortDescription: "A rugged suede outdoor slip-on shown in yellow, brown and black colourways.",
    description: "A suede outdoor slip-on with a light collar and rugged lugged sole. The supplied photos show yellow, brown and black colourways. Ask us which colour and size is currently available.",
    keywords: ["slip-ons", "suede shoes", "outdoor shoes", "yellow shoes", "brown shoes", "black shoes", "men's footwear"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-016",
    name: "Graphic Pocket T-Shirt",
    category: "mens-clothing",
    type: "T-Shirts",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Multiple Colours",
    sizes: "",
    images: ["images/products/et-016-1.jpg"],
    shortDescription: "A casual crewneck tee with a pocket-detail graphic, available in multiple colours.",
    description: "A relaxed crewneck T-shirt with a chest pocket/detail graphic. The supplied photo shows several colour options. Ask us for the available colours and sizes.",
    keywords: ["t-shirt", "tee", "crewneck", "pocket tee", "graphic tee", "casual wear", "men's clothing"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-017",
    name: "Textured Zip-Collar Polo — Mint Green",
    category: "mens-clothing",
    type: "Polo Shirts",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Mint Green",
    sizes: "",
    images: ["images/products/et-017-1.jpg"],
    shortDescription: "A mint-green textured polo with a short zip collar.",
    description: "A textured short-sleeve polo in mint green with a short zip collar. A clean smart-casual layer that can work with denim or tailored trousers.",
    keywords: ["polo", "zip polo", "textured polo", "mint green", "smart casual", "men's clothing"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-018",
    name: "Patterned Textured Polo — Grey / White",
    category: "mens-clothing",
    type: "Polo Shirts",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Grey / White",
    sizes: "",
    images: ["images/products/et-018-1.jpg"],
    shortDescription: "A grey and white patterned textured polo with a clean collar.",
    description: "A short-sleeve polo with a subtle grey and white patterned texture. Designed as an easy smart-casual option for everyday wear.",
    keywords: ["polo", "textured polo", "patterned polo", "grey polo", "white polo", "smart casual", "men's clothing"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-019",
    name: "Fleece Pullover Hoodie — White",
    category: "mens-clothing",
    type: "Hoodies",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "White",
    sizes: "",
    images: ["images/products/et-019-1.jpg"],
    shortDescription: "A clean white fleece pullover hoodie for casual layering.",
    description: "A white fleece pullover hoodie with a simple, relaxed silhouette. An easy layer for cooler evenings and everyday casual wear.",
    keywords: ["hoodie", "pullover", "fleece", "white hoodie", "casual wear", "men's clothing"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-020",
    name: "All-Black Cushioned Trainer",
    category: "mens-footwear",
    type: "Trainers",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Black",
    sizes: "",
    images: ["images/products/et-020-1.jpg"],
    shortDescription: "An all-black cushioned trainer with a bold athletic sole.",
    description: "An all-black athletic-style trainer with a layered upper and prominent cushioned sole. A versatile option when you want a clean black footwear base.",
    keywords: ["trainers", "black trainers", "black sneakers", "cushioned shoes", "athletic shoes", "men's footwear"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-021",
    name: "SD Logo Mesh Trucker Cap — Navy",
    category: "accessories",
    type: "Caps",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Navy / Yellow",
    sizes: "",
    images: ["images/products/et-021-1.jpg"],
    shortDescription: "A navy mesh trucker cap with an SD-style front logo.",
    description: "A navy and mesh trucker-style cap with a contrasting front logo patch and adjustable rear closure. Ask about current colour and availability.",
    keywords: ["cap", "trucker cap", "mesh cap", "navy cap", "accessories", "men's accessories"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-022",
    name: "Africa Map Mesh Trucker Cap",
    category: "accessories",
    type: "Caps",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Charcoal / Multicolour",
    sizes: "",
    images: ["images/products/et-022-1.jpg"],
    shortDescription: "A dark mesh trucker cap featuring an embroidered Africa map motif.",
    description: "A charcoal mesh trucker-style cap with an embroidered Africa map motif on the front. An easy casual accessory with an adjustable back.",
    keywords: ["cap", "trucker cap", "Africa cap", "mesh cap", "charcoal cap", "accessories"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-023",
    name: "Acid-Wash Jeans — Black / Charcoal",
    category: "mens-clothing",
    type: "Jeans",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Black / Charcoal",
    sizes: "",
    images: ["images/products/et-023-1.jpg"],
    shortDescription: "Black and charcoal acid-wash jeans with a worn-in finish.",
    description: "A black and charcoal acid-wash jean with a faded, textured finish. An easy casual option for pairing with tees, polos and sneakers.",
    keywords: ["jeans", "black jeans", "acid wash", "charcoal jeans", "denim", "casual wear", "men's clothing"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-024",
    name: "Trail Running Shoe — Grey / Silver",
    category: "mens-footwear",
    type: "Running Shoes",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Grey / Silver",
    sizes: "",
    images: ["images/products/et-024-1.jpg"],
    shortDescription: "A grey and silver trail-style running shoe with a technical upper.",
    description: "A grey and silver trail-style shoe with a technical layered upper and rugged outsole. A practical-looking option for active and outdoor use. Ask about available sizes and current price.",
    keywords: ["running shoes", "trail shoes", "grey sneakers", "silver shoes", "sports shoes", "men's footwear"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-025",
    name: "Colour-Blocked Striped T-Shirt",
    category: "mens-clothing",
    type: "T-Shirts",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Multiple Colourways",
    sizes: "",
    images: ["images/products/et-025-1.jpg"],
    shortDescription: "A colour-blocked striped crewneck tee shown in several colour combinations.",
    description: "A short-sleeve crewneck T-shirt with broad colour-blocked stripes. The supplied photo shows several colour combinations; ask for the available options and sizes.",
    keywords: ["t-shirt", "tee", "striped tee", "colour block", "crewneck", "casual wear", "men's clothing"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-026",
    name: "Basic Chest-Patch T-Shirt",
    category: "mens-clothing",
    type: "T-Shirts",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Multiple Colours",
    sizes: "",
    images: ["images/products/et-026-1.jpg"],
    shortDescription: "A clean short-sleeve crewneck tee with a small chest patch/detail.",
    description: "A simple short-sleeve crewneck T-shirt with a small chest patch/detail. The supplied photo shows several colour options. Ask for available colours and sizes.",
    keywords: ["t-shirt", "tee", "crewneck", "basic tee", "chest patch", "casual wear", "men's clothing"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-027",
    name: "Textured Shirt-Jacket",
    category: "mens-clothing",
    type: "Shirt-Jackets",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Cream, Tan, Green, Grey",
    sizes: "3XL–5XL",
    images: ["images/products/et-027-1.jpg"],
    shortDescription: "A textured shirt-jacket shown in cream, tan, green and grey. Sizes 3XL–5XL.",
    description: "A textured shirt-jacket/overshirt designed as a versatile outer layer. The supplied photo shows cream, tan, green and grey colourways, with sizes 3XL to 5XL visible.",
    keywords: ["shirt jacket", "overshirt", "shacket", "textured shirt", "3XL", "4XL", "5XL", "plus size", "men's clothing"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-028",
    name: "Slim-Fit Denim Jeans — Medium Wash",
    category: "mens-clothing",
    type: "Jeans",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Medium Wash Blue",
    sizes: "",
    images: ["images/products/et-028-1.jpg"],
    shortDescription: "Medium-wash blue slim-fit denim with a clean everyday finish.",
    description: "A medium-wash blue jean with a slim-fit silhouette and clean everyday finish. A versatile denim option for casual and smart-casual outfits.",
    keywords: ["jeans", "blue jeans", "slim fit", "denim", "medium wash", "men's clothing", "casual wear"],
    featured: true,
    newArrival: true,
    available: true
  },
  {
    id: "et-029",
    name: "Athletic Sneaker — Red / Black / Purple",
    category: "mens-footwear",
    type: "Sneakers",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Red / Black / Purple",
    sizes: "",
    images: ["images/products/et-029-1.jpg"],
    shortDescription: "A bold athletic-style sneaker in red, black and purple.",
    description: "A multi-colour athletic-style sneaker combining red, black and purple panels with a sporty silhouette. Ask about available sizes and current price.",
    keywords: ["sneakers", "athletic sneakers", "red sneakers", "black sneakers", "purple", "men's footwear"],
    featured: false,
    newArrival: true,
    available: true
  },
  {
    id: "et-030",
    name: "Embossed Suede Basketball-Style Sneaker — Black",
    category: "mens-footwear",
    type: "Sneakers",
    brand: "",
    price: 0,
    priceOnRequest: true,
    currency: "KES",
    color: "Black",
    sizes: "",
    images: ["images/products/et-030-1.jpg"],
    shortDescription: "A black suede basketball-style sneaker with an embossed upper.",
    description: "A black high-top basketball-style sneaker with an embossed suede upper and tonal construction. A strong everyday option for casual streetwear looks.",
    keywords: ["sneakers", "basketball shoes", "high top", "black sneakers", "suede sneakers", "embossed", "men's footwear"],
    featured: false,
    newArrival: true,
    available: true
  }
];